language: ruby
cache: bundler
rvm:
  - 2.3.0
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - "bundle exec jekyll build"
before_deploy:
  - "nvm install v7.10.0"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"